name: Call reusable workflow

on:

  workflow_dispatch:
  
  push:
    branches:
      - main

jobs:
  remote:
    uses:  hybridaccess/called/.github/workflows/called.yaml@master
    with:
      name: test
    secrets:
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      BACKEND_CONFIG: ${{ secrets.BACKEND_CONFIG }}
