name: Call reusable workflow

on:
  workflow_dispatch:
  
env:
  dev: NONPROD
  prd: PROD

jobs:
  remote:
    uses:  hybridaccess/shared-workflow/.github/workflows/called.yml@master
    with:
      name: test
    secrets:
      SUBSCRIPTION_ID: ${{ secrets.$dev_SUBSCRIPTION_ID }}
      BACKEND_CONFIG: ${{ secrets.$prd_BACKEND_CONFIG }}
