name: Call reusable workflow

on:
  workflow_dispatch:

jobs:
  remote:
    uses:  hybridaccess/shared-workflow/.github/workflows/called.yml@master
    with:
      name: test
    secrets:
      SUBSCRIPTION_ID: ${{ secrets.NONPROD_SUBSCRIPTION_ID }}
      BACKEND_CONFIG: ${{ secrets.NONPROD_BACKEND_CONFIG }}
