name: Call reusable workflow

on:

  workflow_dispatch:
  
  push:
    branches:
      - master

jobs:
  remote:
    uses:  hybridaccess/shared-workflow/.github/workflows/called.yml
    with:
      name: test
    secrets:
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      BACKEND_CONFIG: ${{ secrets.BACKEND_CONFIG }}
