name: Read secrets into env vars

env:
  dev: NONPROD_BACKEND_CONFIG
  prd: PROD_SUBSCRIPTION_ID
  mysec: ${{ secrets.AKAMAI }}
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  dump:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: filter
        run: |
          set -x
          echo "dev: ${{ env.dev }}" | sed 's/./& /g' 
          echo "prd: ${{ env.prd }}" | sed 's/./& /g' 
          echo "mysec: ${{ env.mysec }}" | sed 's/./& /g' 

